name: flutterfire_tutorial
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  firebase_analytics: ^1.0.3
  cloud_firestore: ^0.7.3
  firebase_ml_vision: ^0.2.0+1

  image_picker: ^0.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
